const headings = ["Cosmetics", "Game Modes", "Creative", "IDK What Else"];
const subheadings = ["View and learn about all Gims, Stickers, Trails, and other cosmetic-based info on the Cosmetics page!", "Access information about all game modes, whether it's Top-Down, Platformer, a Tycoon Twist, and more!", "Learn about Gimkit Creative, as well as its types of Terrain, Devices, Props, and Updates!"];
const links = ["gims.html", "", "", ""];
const cosmeticImage = ["dayOne", "echoAgent", "stripeDoubleGreen", "mustache", "vortexAgent", "grayGradient", "redNinja", "sprinklesRed", "redDeliciousApple", "sunny", "fadedBlueGradient", "glassHalfFull", "whiteAndBlueVerticalStripes", "polkaDotBlueAndYellow", "pinkPaste", "volcanoCracks", "mustachePink", "mountainAndSun", "camoTan", "redDinoCostume", "stripeDoubleRed", "coolRedBlueGradient", "pencilPack", "glyphsYellowBrown", "camoBlue", "purplePaste", "galaxy", "luchador", "fox", "rockyWest", "pumpkin", "mummy", "ghostCostume", "fifthBirthday", "corn", "feast", "pumpkinPie", "frostBuddy", "polkaDotWhiteAndRed", "festiveOnesieBlue", "festiveOnesieGreen", "festiveOnesieRed", "festiveOnesieTan", "hotChocolate", "snowman", "snowglobe", "gift", "polkaDotFestive", "polkaDotFestiveReverse", "mustacheSanta", "firework",  "puzzleYellowPurple", "puzzleGreenBlue", "puzzleOrangeBlue", "puzzleGrayWhite", "puzzleRedGreen", "pirate", "cellGold", "heart", "roses", "detective", "hamster", "leprechaun", "astroHelmet", "constellationPurpleYellow", "constellationBlackWhite", "constellationBlackGreen", "constellationPinkGreen", "constellationYellowPink", "sketch", "mustacheBrown", "yinYang", "fisher", "coffee", "partyPineapple", "construction", "graduate", "graduateBlue", "stripeDoublePurple", "bananaSplit", "rockstar", "rainbowWave",  "mountain", "tent", "goat", "daisy", "climber", "cookie", "zebra", "diamondRainbow", "circuitGreen", "circuitBlue", "circuitGray", "clock", "squiggles", "autumnTree", "crashTestDummy", "stripeDoubleYellow", "witch", "skeleton", "spiderWeb", "trickTreat", "calacaOne", "turkey", "farmer", "knight", "yellowCracksPurple", "arcticFox", "whistle", "penguinBlue", "goldenHotChocolate", "blastball", "blastballGimchester", "blastballKitcelona", "pufferJacket", "christmasTree", "rudolph", "snowball", "santaClaus", "causticWaterBlue", "causticWaterRed", "causticWaterGreen", "causticWaterCaribe", "causticWaterOcean", "causticWaterPurple", "taco", "gimKing", "sketchBlue", "valenTime", "referee", "pilot", "sprinklesChocolate", "miningCart", "rainCloud", "watermelon", "terrainBlock", "floatingTube", "miner", "sproutingFlower", "discoBall", "luckyClover", "shark", "axolotlPink", "axolotlBlue", "axolotlYellow", "astroCaptain", "tuxedo", "blacksmith", "eclipse", "redDino", "sockGremlin", "dotsBluePink", "dotsGreenBlue", "dotsPurpleGreen", "dotsPurpleYellow", "dotsYellowOrange", "dotsYellowPurple", "crayonBox", "8bit", "8bitPurple", "8bitYellow", "8bitRed", "8bitBlue", "strawberry", "brainJar", "viking", "marshmallow", "zombieTruckPurple", "rollercoaster", "pufferFish", "zombieGeckoGreen", "8bitFox", "defender", "rainDrop", "doc", "golden", "costumeGimfish", "costumeOctopus", "vanGogh", "beetle", "mantis", "wavesFire", "wavesCalmSea", "wavesApple", "wavesNight", "wavesBorealis", "tennisPlayer", "bigEye", "vampire", "wraith", "frankengim", "deadMariachi", "7thAnniversary", "incognito", "smashedPotatoes", "atom", "wavesCandy", "wavesFantasy", "wavesIcecream", "angel", "ant", "bat", "costumeBear", "bee", "broccoli", "burger", "butterfly", "calacaTwo", "calacaThree", "camoGreen", "caramelApple", "costumeCat", "caterpillar", "glyphsOrangeBlue", "cellBlue", "costumeChicken", "circusBall", "clown", "dragon", "elf", "costumeFish", "gamerGreen", "gamerPink", "gamerPurple", "gamerYellow", "picasso", "hotdogVendor", "ladybug", "mondrian", "moon", "moth", "pinata", "pretzel", "racoon", "redPanda", "toaster", "tourist", "yarn", "sentryRobot", "frozenMummy", "evilPlantGreen", "evilPlantPink", "mayorCoal", "zombieBasicGrey", "zombieCactusGreen", "zombieGeckoGrey", "zombieTornadoBrown", "zombieRockGrey", "zombieCageGrey", "zombieTruckGrey", "zombieBasicTan", "zombieCactusBrightGreen", "zombieTornadoGreen", "zombieRockDarkGrey", "zombieCageTan", "zombieTruckGreen", "zombieBasicPurple", "zombieCactusPurple", "zombieGeckoPurple", "zombieTornadoPurple", "zombieRockPurple", "zombieCagePurple"];
const gadgetImage = ["snowball_launcher", "zapper", "slingshot", "muffin_launcher", "quantum_portal", "evil_eye", "blaster", "pickaxe", "pixel", "rock", "cactus", "tornado", "hammer"];
const images = [`https://www.gimkit.com/assets/map/characters/spine/preview/${cosmeticImage[Math.floor(Math.random() * 262)]}.png`, `https://www.gimkit.com/assets/map/inventory/weapons/${gadgetImage[Math.floor(Math.random() * 13)]}.png`, "https://www.gimkit.com/assets/map/characters/spine/preview/construction.png"];
const contentContainer = document.getElementById("contentContainer");
headings.forEach((heading, index) => {
    const contentDiv = document.createElement("div");
    contentDiv.style.display = "flex";
    contentDiv.style.alignItems = "center";
    contentDiv.style.padding = "1vw 1vw";
    contentDiv.style.margin = "3vw auto";
    contentDiv.style.backgroundColor = "#00000033";
    contentDiv.style.borderRadius = "5vw";
    const textDiv = document.createElement("div");
    textDiv.style.width = "65vw";
    textDiv.style.boxSizing = 'border-box';
    textDiv.style.textAlign = "left";
    const h1 = document.createElement('h1');
    h1.style.fontSize = '6vw';
    h1.style.margin = '0';
    h1.style.padding = '0';
    h1.style.color = '#ffffffcc';
    h1.textContent = heading;
    const h2 = document.createElement('h2');
    h2.style.fontSize = '1.5vw';
    h2.style.fontWeight = '400';
    h2.style.fontFamily = "'Fira Sans', sans-serif";
    h2.style.margin = 0;
    h2.style.padding = 0;
    h2.style.color = "#ffffffcc";
    h2.innerHTML = `${subheadings[index]} <a href="${links[index]}" style="font-size: 1.5vw; font-weight: 400; font-family: 'Fira Sans', sans-serif; margin: 0; padding: 0; color: #0088ffcc; text-decoration: none;">Check It Out Now! ></a>`;
    textDiv.appendChild(h1);
    textDiv.appendChild(h2);
    const imgDiv = document.createElement('div');
    imgDiv.style.width = '30%';
    imgDiv.style.boxSizing = 'border-box';
    imgDiv.style.textAlign = 'center';
    const img = document.createElement('img');
    img.src = images[index];
    img.style.height = '20vw';
    img.style.width = '20vw';
    img.style.padding = '0';
    img.style.margin = '0';
    img.style.transform = "rotate(-5deg)";
    imgDiv.appendChild(img);
    if (index % 2 === 0) {
        contentDiv.appendChild(textDiv);
        contentDiv.appendChild(imgDiv);
        h1.style.textAlign = "left";
        h2.style.paddingLeft = "5vw";
        h1.style.paddingLeft = "5vw";
        img.style.transform = "scaleX(-1) rotate(-5deg)";
    } else {
        contentDiv.appendChild(imgDiv);
        contentDiv.appendChild(textDiv);
        h1.style.textAlign = "left";
    }
    contentContainer.appendChild(contentDiv);
});